[Cache]
 Enable = true

[Storage]
 Type = "boltdb"
 Node = "127.0.0.1"
 Hostname = ""
 HttpPort = 12345
 TcpPort = 12346
 Cluster = []
 DataPath = ["D:\\dev\\silver\\testdata1","D:\\dev\\silver\\testdata2"]