nodeName: "node1"
nodeId: 1
nodeAddr:
  httpAddr: "127.0.0.1:12345"
  cluAddr: "127.0.0.1:7947"
  tcpAddr: "127.0.0.1:12346"
dataDir: ["/Volumes/info/dev/silver/testdata1/","/Volumes/info/dev/silver/testdata2/"]
indexDir: ["/Volumes/info/dev/silver/index1/"]
wal:
  walDir: "/Volumes/info/dev/silver/wal1/"
  ttl: 1
  nodeNums: 100
  listNums: 500
  size: 100
flush:
  count: 100000
  ttl: 3
heatbeat:
  timeout: 5
  tick: 5
metastore:
  metaAddr: ["127.0.0.1:2379"]
  metaPrefix: "/silver/metaData/"
  nodePrefix: "/sliver/node/"
  timeout : 10
  heartbeat: 5
discovery:
  timeout: 10
compressed: true
compressCount: 100000
indexed: true
